import random
print('dice sim in pyhton V1.01')
print('made by aniketh shet')
dice = random.randint(1, 6)
while True:
    ask = str(input('do you want to start the dice simulator(y/n):'))
    if ask =='y':
            print('ok!')
            if dice == 1:
                print('|-----------------------------------|')
                print('|                                   |')
                print('|                                   |')
                print('|                                   |')
                print('|                                   |')
                print('|                0                  |')
                print('|                                   |')
                print('|                                   |')
                print('|                                   |')
                print('|                                   |')
                print('|-----------------------------------|')
            if dice == 2:
                print('|-----------------------------------|')
                print('|                                   |')
                print('|                                   |')
                print('|                0                  |')
                print('|                                   |')
                print('|                                   |')
                print('|                0                  |')
                print('|                                   |')
                print('|                                   |')
                print('|                                   |')
                print('|                                   |')
                print('|-----------------------------------|')
                if dice == 3:
                    print('|-----------------------------------|')
                    print('|                                   |')
                    print('|                                   |')
                    print('|                0                  |')
                    print('|                                   |')
                    print('|                0                  |')
                    print('|                                   |')
                    print('|                0                  |')
                    print('|                                   |')
                    print('|                                   |')
                    print('|                                   |')
                    print('|                                   |')
                    print('|-----------------------------------|')
                    if dice == 4:
                        print('|-----------------------------------|')
                        print('|                                   |')
                        print('|                                   |')
                        print('|            0        0             |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|            0        0             |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|-----------------------------------|')
                    if dice == 5:
                        print('|-----------------------------------|')
                        print('|                                   |')
                        print('|                                   |')
                        print('|           0         0             |')
                        print('|                                   |')
                        print('|                0                  |')
                        print('|                                   |')
                        print('|           0         0             |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|-----------------------------------|')
                    if dice == 5:
                        print('|-----------------------------------|')
                        print('|                                   |')
                        print('|                                   |')
                        print('|           0    0    0             |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|           0    0    0             |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|                                   |')
                        print('|-----------------------------------|')
    else:
        print('ok! see you next time!')
        break
